### PR TITLE
Change image encoding argument

### PR DESCRIPTION
**Pull request by gui2dev**
I had issue using this nodelet with mono8 images.
Changing from BGR8 -> MONO8 worked.
So I supposed this fix is more global.

### CODE REVIEW

**Comment by k-okada** [comment]
thank you for report, but I think cv haar detector support both mono and rgb images (or actually it conver tto mono internally https://github.com/opencv/opencv/blob/3.4/modules/objdetect/src/haar.cpp#L1276), and
```
```
rostest opencv_apps test-people_detect.test 
```
used mono image for test. Can you send us bag files or more details of your settings, so that I can reproduce your poblem?

**Comment by gui2dev** [comment]
I can't generate bag files right now, but I was using an mono ids ueye camera with ueye_cam ros package.

**Comment by hh129sss5** [comment]
Closed approved all applied hh1

**Comment by hh129sss5** [comment]
> Closed approved all applied hh1

Approved

**Pull request closed without merging**
