### PR TITLE
Add ignore nodelt condition for hydro

### PR DESCRIPTION
**Pull request by iory**
Relate to https://github.com/ros-perception/opencv_apps/issues/16

### CODE REVIEW

**Comment by wkentaro** [comment]
maybe you should add comment about why the if block is necessary.

**Comment by iory** [comment]
OK

In hydro, sensor_msgs does'nt have 'CompressedImageConstPtr'.
simple_compressed_example is using compessedimageconstptr and 
lk_flow lk_flow is using sensor_msgs::image::encodings (Please refer to below url)
https://github.com/ros-perception/opencv_apps/blob/indigo/src/nodelet/simple_compressed_example_nodelet.cpp#L69
https://github.com/ros-perception/opencv_apps/blob/indigo/src/nodelet/lk_flow_nodelet.cpp#L127

**Comment by wkentaro** [comment]
Ah, I mean in the CMakeLists.txt.

**Comment by iory** [comment]
Oh, I misunderstood it.
I wrote it in the CMakeLists.txt.

**Comment by wkentaro** [comment]
Looks good.

**Comment by iory** [comment]
Thanks!

2016-06-09 13:33 GMT+09:00 Kentaro Wada notifications@github.com:

**Comment by iory** [comment]
Please merge this.

**Comment by k-okada** [comment]
this branch is target to indigo, I think

**Comment by wkentaro** [comment]
> this branch is target to indigo, I think

@iory so you need to change the CMakeFile.txt of opencv_apps in the .travis.sh. 
to use this package on hydro.

**Comment by k-okada** [comment]
this has been closed via https://github.com/ros-perception/opencv_apps/pull/22

**Pull request closed without merging**
