### PR TITLE
Add pyramids_nodelet

### PR DESCRIPTION
**Pull request by iory**
Add pyramids_nodelet ros version
https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/ImgProc/Pyramids.cpp

### CODE REVIEW

**Comment by k-okada** [comment]
please add pyramids_result.png so that we can put that imgae on http://wiki.ros.org/opencv_apps

**Comment by iory** [comment]
OK! I upload it.
pyramids_result

**Comment by furushchev** [comment]
need rebase origin/indigo (see #45)

**Comment by iory** [comment]
rebased

**Comment by iory** [comment]
Please merge this.

**Comment by k-okada** [comment]
https://cloud.githubusercontent.com/assets/4690682/18719025/948e5cee-8060-11e6-99a1-57dc08adf995.png
Is this the result?

**Comment by iory** [comment]
pyramids nodelet changes image size.
So, the result is correct.
The image size are  changed

**Comment by k-okada** [comment]
iory, iory, iory,....
If you wan to show "pyramid image", usually people preare something like
this.
http://labs.eecs.tottori-u.ac.jp/sd/Member/oyamada/OpenCV/html/_images/messipyr.jpg
http://en.pudn.com/downloads183/sourcecode/graph/texture_mapping/detail857700_en.html

--
◉ Kei Okada


2017-03-30 16:02 GMT+09:00 iory <notifications@github.com>:

**Comment by iory** [comment]
Oh, I see. I learned that.
How about this image
after

**Comment by iory** [comment]
border version
after

**Comment by k-okada** [comment]
very nice !!! can you also show the script to write this file? I'd like to think if we can add that to https://github.com/ros-perception/opencv_apps/pull/37/files#diff-5d2a58ed88aad71aded9ee0e0a9590f9R17

**Comment by iory** [comment]
Can we execute imagemagick code? Is this not general solution?
```
convert pyramids_result_x4.png pyramids_result_x3.png -bordercolor white -border 20 -geometry +0+0 -composite pyramids_result_x2.png -bordercolor white -border 20 -geometry +20+20 -composite pyramids_result_x1.png -bordercolor white -border 20 -geometry +40+40 -composite  pyramids_result.jpg
```

**Comment by k-okada** [comment]
one solution is to use https://github.com/ros-perception/opencv_apps/pull/57 (or this change may too much)
anyway we can update test code to output pyramids_result_x4.png pyramids_result_x3.png,pyramids_result_x2.png ...

**Comment by iory** [comment]
Applying adding image nodelet's result is following.

pyramids_result

**Comment by k-okada** [comment]
you can change `alpha` parameter

**Comment by k-okada** [comment]
@iory please use alpha to get better result images

**Comment by k-okada** [comment]
@iory please update roswiki documents

**Pull request merged**
