### PR TITLE
[face_detection_nodelet.cpp] publish face roi image

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
rebased origin/indigo (see #45)

**Comment by k-okada** [comment]
please update roswiki -> http://wiki.ros.org/opencv_apps#face_detection
and also update test code https://github.com/ros-perception/opencv_apps/blob/indigo/test/test-face_detection.test#L18-L20

**Comment by furushchev** [comment]
updated test code https://github.com/ros-perception/opencv_apps/pull/47

**Comment by furushchev** [comment]
updated roswiki http://wiki.ros.org/action/info/opencv_apps?action=diff&rev2=18&rev1=17

**Comment by k-okada** [comment]
i see, how about to add only
https://github.com/ros-perception/opencv_apps/pull/47/files#diff-f36def5ba71d78aa656285f4bb9e0d23R22
node, and do not run publishtest, because at this moment, we only
publish and save `face_detection/image` but did not actually test if
that is published on travis, we just run test code locally and see if
we have output image file.
Please also add face image file corresponds to

## http://wiki.ros.org/opencv_apps?action=AttachFile&do=get&target=face_detection.png

◉ Kei Okada

2016-10-16 22:50 GMT+09:00 Furushchev notifications@github.com:

**Pull request merged**
