### PR TITLE
Switch to hpp headers of pluginlib

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by k-okada** [comment]
@jspricke thanks for fix, which version of calssloader requires hpp header?

**Comment by jspricke** [comment]
Hi Kei, the .h headers where deprecated 2018 in https://github.com/ros/class_loader/commit/7fd8c42 or version 0.4.0 and dropped in https://github.com/ros/class_loader/commit/757369e or version 1.1.0 (ROS 2).

**Comment by k-okada** [comment]
merged via #139

**Comment by nuclearsandwich** [comment]
I think it is actually #140 which includes these changes.

**Pull request closed without merging**
