### PR TITLE
Add lk flow params trackbar

### PR DESCRIPTION
**Pull request by taichiH**
Add track-bar to dynamically change parameters of goodFeaturesToTrack.

### CODE REVIEW

**Comment by iory** [comment]
Thank you for your contribution!

In this code, you inititialized value at first (https://github.com/ros-perception/opencv_apps/pull/78/files#diff-33f513cd81a102869702f7300479603bR325) .
But, I think this initialization is not needed.

When we initialize dynamic reconfigure server, parameters are initialized by ```cfg```'s default parameters.
https://github.com/ros/dynamic_reconfigure/blob/master/include/dynamic_reconfigure/server.h#L174-L193

After that, we call ```setCallback``` function.
This function internally calls callback function (i.e ```reconfigureCallback``` function).
https://github.com/ros/dynamic_reconfigure/blob/master/include/dynamic_reconfigure/server.h#L85

So, initialized values manually are not needed.

**Review by iory — CHANGES_REQUESTED** [review]
Please delete initialization of params.

**Review by iory — APPROVED** [review]

**Comment by iory** [comment]
@taichiH 
This PR's test failes and the test was fixed by following PR.
https://github.com/ros-perception/opencv_apps/pull/79

Please rebase this PR.

**Comment by iory** [comment]
```git pull --rebase origin indigo```
```git push -f taichiH add_lk_flow_params_trackbar```

**Comment by taichiH** [comment]
rebased 
@k-okada 
Travis passed. Please merge this.

**Comment by k-okada** [comment]
@taichiH  please rebase origin/master to check on melodic and update http://wiki.ros.org/opencv_apps for new features.

**Comment by k-okada** [comment]
updated http://wiki.ros.org/opencv_apps#lk_flow and merged

**Pull request merged**
