### PR TITLE
Smoothing filter

### PR DESCRIPTION
**Pull request by iory**
related to
https://github.com/ros-perception/opencv_apps/pull/25

smoothing

### CODE REVIEW

**Comment by k-okada** [comment]
please write code on top of
https://github.com/ros-perception/opencv_apps/pull/25 and also add lines
like // https://github.com/Itseez/opencv/blob/2.4/samples/cpp/lk_demo.cpp,
to stop updating code. because if we have "original sample code", if some
one look at code and want to fix them, we can say this code is based on
original code, so I understand you want to change this, but do not have to.
If not, we'll have never-ending code updating process.

## 

◉ Kei Okada

**Comment by iory** [comment]
OK, I fixed those points.

**Comment by k-okada** [comment]
fixed in #32

**Comment by k-okada** [comment]
@iory please add info to wiki page http://wiki.ros.org/opencv_apps

**Pull request closed without merging**
