### PR TITLE
[face_detection_nodelet.cpp] fix: face/eye origin

### PR DESCRIPTION
**Pull request by furushchev**
In current code, face / eye rectangles origin are each center points.
Since face and eyes message is defined as rectangle, these should be the origin of each components.

``` bash
$ rosmsg show opencv_apps/Face
opencv_apps/Rect face
  float64 x
  float64 y
  float64 width
  float64 height
opencv_apps/Rect[] eyes
  float64 x
  float64 y
  float64 width
  float64 height
```

### CODE REVIEW

**Comment by furushchev** [comment]
irrelevant error?

``` bash
cd /home/travis/catkin_ws/build/opencv_apps/test && rosbag reindex vslam_tutorial.bag --output-dir /home/travis/catkin_ws/src/opencv_apps/test
ERROR reading vslam_tutorial.bag: [Errno 2] No such file or directory: 'vslam_tutorial.bag'
```

**Comment by k-okada** [comment]
Yes, you're right, but at same time, people usually uses 'center of face' , and do not care about rectangle, so for such people, publishing the 'origin' of rectangle seems error code. How about publich face_centers too?
plesase add comment within the code and explain faces is the rectangle and x,y is the left-top (?) of the rectangle.
reindex vslam_tutorial.bag is downloaded during compile time, so it is just failed to download, I think

**Comment by furushchev** [comment]
@k-okada OK, I added `face_center` and `eyes_center` to `Face` message with explanation. Please review.

**Comment by furushchev** [comment]
rebased origin/indigo (see #45)

**Comment by furushchev** [comment]
@k-okada kindly ping to a maintainer.

**Comment by furushchev** [comment]
@k-okada Any comment?

**Comment by k-okada** [comment]
this is API breaking PR, so I'll merge with other braking PRs

## 

◉ Kei Okada

2016-10-14 21:08 GMT+09:00 Furushchev notifications@github.com:

**Comment by furushchev** [comment]
@k-okada Now I see. Please add a label for that.

**Comment by furushchev** [comment]
Closed. Now face recognition feature was merged and is used by some packages. I think it's rather better to keep this unchanged.

**Pull request closed without merging**
