### PR TITLE
Support OpenCV 4

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by k-okada** [comment]
@jspricke great! do you know how to check opencv4 on 18.04 or 16.04?
I'd like to update
https://github.com/ros-perception/opencv_apps/blob/indigo/.travis.sh#L62-L69 and let Travis to check CV4

**Comment by k-okada** [comment]
this also breaks current build

https://travis-ci.org/ros-perception/opencv_apps/jobs/602012404?utm_medium=notification&utm_source=github_status
```
Errors     << opencv_apps:make /home/travis/catkin_ws/logs/opencv_apps/build.make.000.log
/home/travis/catkin_ws/src/opencv_apps/src/nodelet/face_recognition_nodelet.cpp: In member function 'void opencv_apps::FaceRecognitionNodelet::configCallback(opencv_apps::FaceRecognitionNodelet::Config&, uint32_t)':
/home/travis/catkin_ws/src/opencv_apps/src/nodelet/face_recognition_nodelet.cpp:621:17: error: 'class cv::face::FaceRecognizer' has no member named 'set'
         model_->set("threshold", config.model_threshold);
                 ^~~
make[2]: *** [CMakeFiles/opencv_apps.dir/src/nodelet/face_recognition_nodelet.cpp.o] Error 1
make[1]: *** [CMakeFiles/opencv_apps.dir/all] Error 2
```

**Comment by mintar** [comment]
The test failure on hydro (Ubuntu Precise) is unrelated to this PR. It's caused by `python-vcstool`, which contains a control.tar.xz file, which in turn requires dpkg 1.17.5ubuntu5.8 or greater ([Launchpad bug 1730627](https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627)). That won't be released into precise, however.

The buildfarm for precise is long dead, so I don't think this will ever be fixed. Therefore, the easiest workaround would be to remove hydro from the .travis.yml.

**Comment by jspricke** [comment]
Thanks a lot for @mintar for finding the Travis issue!

> @jspricke great! do you know how to check opencv4 on 18.04 or 16.04?

You could use Debian unstable for that (all dependencies are in there ;) ).

**Comment by mintar** [comment]
Hmmm... 

3 monts ago, the test still worked (with python-vcstools 0.1.40-1): https://travis-ci.org/ros-perception/opencv_apps/jobs/568615356#L645

Now it breaks (with python-vcstools 0.1.42-1): https://travis-ci.org/ros-perception/opencv_apps/jobs/602348692#L650

So somebody uploaded a new version to the ros package repository for precise!?!

**Comment by mintar** [comment]
The python-vcstools bug is ticketed here: https://github.com/vcstools/vcstools/issues/157

**Comment by k-okada** [comment]
@jspricke sorry for  trouble and @mintar thinks for help.
To fix this issue until https://github.com/vcstools/vcstools/issues/157#issuecomment-546277984, 
I have merged the origin/master by https://github.com/ros-perception/opencv_apps/pull/98, so now it should work.

**Comment by mintar** [comment]
@k-okada : vcstools/vcstools#157 is now solved, so #98 is not required anymore. Anyway, all tests in this PR pass, and I think it's ready to merge.

**Comment by jspricke** [comment]
Already in master.

**Comment by hh129sss5** [comment]
Granted all applied hh1

**Pull request closed without merging**
